### ISSUE TITLE
Cannot pass multiple passages

### ISSUE THREAD

**Issue by sayef** [sebastian-hofstaetter/intra-document-cascade#1]
Hi,

Thanks for this awesome repo. I was playing around with the colab notebook. I tried passing multiple passages at once. The following error was thrown.

```
in forward(self, query, document, use_fp16, output_secondary_output)
    125         total_chunks=chunked_ids_unrolled.shape[0]
    126 
--> 127         packed_query_ids = query["input_ids"].unsqueeze(1).expand(-1,chunk_pieces,-1).reshape(-1,query["input_ids"].shape[1])[packed_indices]
    128         packed_query_mask = query["attention_mask"].unsqueeze(1).expand(-1,chunk_pieces,-1).reshape(-1,query["attention_mask"].shape[1])[packed_indices]
    129 

IndexError: The shape of the mask [6] at index 0 does not match the shape of the indexed tensor [3, 9] at index 0
```

I am not sure if it's expected behavior or an actual bug. But it would be nice to pass multiple passages at once.

Reproducing the error:

```
passages = ...  # array of string
query = ... # string

tokenized_query = tokenizer(query, return_tensors="pt", max_length=30, truncation=True)
tokenized_passages = tokenizer(passages, return_tensors="pt", max_length=2000, padding=True, truncation=True)

# rest is same as notebook
```

Thanks in advance. 
Regards,
Sayef

**Comment by sebastian-hofstaetter** [comment]
Hi Sayef,

Thanks for your interest in the IDCM model! 

By multiple passages, do you mean a batched way, where you have multiple query document pairs and want to run them all at once? Or do you mean you have 1 query and 1 document, but you already split the passages and want to run the IDCM model on the list of split passages?

- For the first you just have to have multiple queries as well (for each document 1 query)
- For the second, that is currently not supported, but could be if you re-write the model code - we assume you input one long document sequence and we split it inside the model (right before the error happened), you could rewire that to take the list of passages instead - however it might get tricky with packing the passages together if you want to do a batched passage list inference.

Best,
Sebastian

**Comment by sayef** [comment]
Thanks for getting back so quickly. I am referring a situation, where I have one query, and multiple documents (let's say few Wikipedia pages). I would like to see the similarities with my query and wiki pages. 

From your reply, what I have understood that I have to repeat query `n` times where `n` is the number of passages. 

```
queries = [query] * len(passages)
model(queries, passages)
```

and it works.

**Comment by sebastian-hofstaetter** [comment]
Exactly, great! happy to help :)
